### ISSUE TITLE
Installed global dependency but still get an error

### ISSUE THREAD

**Issue by neo4u** [cacois/flask-angular2-starter#1]
npm WARN webpack-dev-server@2.1.0-beta.12 requires a peer of webpack@^2.1.0-beta.26 but none was installed.

Any idea as to what can be done for this issue?

**Comment by cacois** [comment]
Yep - this is due to some issues with compatibility in recent webpack/typescript updates. Pull latest - I've updated to lock the versions to those that work for now, instead of trusting the '^' version to be compatible. 

Let me know if you run into any more trouble.
