### ISSUE TITLE
Python import error

### ISSUE THREAD

**Issue by neo4u** [cacois/flask-angular2-starter#2]
I am unable to get through the initdb due to the following error. There is some problem importing from the user.py file. Do you have know what this problem could be?

This is when I type:
`python3 manage.py initidb`

```
Traceback (most recent call last):
  File "manage.py", line 2, in <module>
    from flask_app.app import app
  File "/Users/xxx/personal_git_repos/flask-angular2-starter/src/server/flask_app/__init__.py", line 6, in <module>
    from .models import Role, User
  File "/Users/xxx/personal_git_repos/flask-angular2-starter/src/server/flask_app/models/__init__.py", line 2, in <module>
    from user import User
ImportError: No module named 'user'
```

**Comment by neo4u** [comment]
I installed the packages on python2 and it worked.

**Comment by cacois** [comment]
Yep - currently only python2 compatible. I'll make a point to do some upgrades soon, python 3 compatibility shouldn't be too challenging.

**Comment by neo4u** [comment]
I modified it to be compatible with python3 instead by changing the imports like so:
```
from user import User
from base import Base 
```
to 
```
from .user import User
from .base import Base
```
Not sure how to make it compatible with both though. Thank you for your quick response.
